### ISSUE TITLE
MultiHelen_v1 data 

### ISSUE THREAD

**Issue by vsooda** [Liusifei/Face_Parsing_2016#3]
Hi sifei,

I want train the helen model, but I can't find `MultiHelen_v1.dat`. Can you add this data, or can you show us how to generate this file?

thank you.

**Comment by jamt9000** [comment]
I would also like to know how to train on Helen, and how to get test images preprocessed in an identical way to the paper for comparison.

Thanks

**Comment by HPL123** [comment]
@vsooda @jamt9000 could you tell me how to use the helen dataset?
